language: python
python: 2.7
sudo: required
branches:
  only:
  - master
before_script:
  - sudo apt-add-repository ppa:swi-prolog/devel -y
  - sudo apt-get update -q
  - sudo apt-get install swi-prolog-nox
script:
  - swipl -s numberlink.pl -g run_tests,halt -t 'halt(1)'
  - cat output/output.txt
