language: python
python: 2.7
sudo: required
branches:
  only:
  - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - build-essential
    - curl
    - chrpath
    - pkg-config
    - ncurses-dev
    - libreadline-dev
    - libedit-dev
    - libgmp-dev
    - libssl-dev
    - unixodbc-dev
    - libarchive-dev
    - libossp-uuid-dev
    - libxext-dev
    - libice-dev
    - libjpeg-dev
    - libxinerama-dev
    - libxft-dev
    - libxpm-dev
    - libxt-dev
    - libdb-dev
    - libpcre3-dev
    - openjdk-8-jdk
    - junit
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - wget http://github.com/SWI-Prolog/swipl/archive/V5.6.34.tar.gz
  - tar xzvf V5.6.34.tar.gz
  - cd swipl-5.6.34
  - ./configure --enable-shared
  - make
  - sudo make install
install:
  - pip install -r requirements.txt
script:  
  - python parsing.py "(2,1,(1: (1,2),(2,2)))"
