language: python
python: 2.7
sudo: required
branches:
  only:
  - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - python2.7-venv
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - wget http://github.com/SWI-Prolog/swipl/archive/V5.6.50.tar.gz
  - tar xzvf V5.6.50.tar.gz
  - cd swipl-5.6.50
  - ./configure --enable-shared
  - make
  - sudo make install
  - python2.7 -m venv venv
  - source venv/bin/activate
install:
  - pip install -r requirements.txt
script:  
  - python parsing.py "(2,1,(1: (1,2),(2,2)))"
