language: python
python: 2.7
branches:
  only:
  - master
before_install:
  - wget http://github.com/SWI-Prolog/swipl/archive/V5.6.34.tar.gz
  - tar xzvf V5.6.34.tar.gz
  - cd swipl-5.6.34
  - ./configure --enable-shared
  - make
  - sudo make install
  - python2.7 -m venv venv
  - source venv/bin/activate
install:
  - pip install -r requirements.txt
script:  
  - python parsing.py "(2,1,(1: (1,2),(2,2)))"
